### PR TITLE
added challenge_06.1.r

### PR DESCRIPTION
**Pull request by codemasta14**

### CODE REVIEW

**Review by dylanjm — CHANGES_REQUESTED** [review]
Thinking about it again, let's rename this challenge to something like `love_letter_challenge.r` and `love_letter_data.txt` Can you also put the input data into the `data` folder. After that, it looks good!

**Comment by codemasta14** [comment]
All done!

**Review by dylanjm — CHANGES_REQUESTED** [review]
Can you move the challenge into user_challenge for the moment? just to keep everything organized.

**Review by dylanjm — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
